### PR TITLE
Issue1415

### LINKED ISSUE #1415: Cannot Remove Favorited Dashboard/Reports
Steps To Reproduce:
1. Boot App (`./gradlew bootRun`)
2. Create and Save Report
3. Favorite Report
4. Delete Report
5. See error message

### PR DESCRIPTION
**Pull request by aklish**
Resolves #1415 

## Description
Cleans up references to dashboards and reports in new life cycle hooks so they can be safely deleted by the client.

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/ReportDeletionHook.kt [hunk 1]
```diff
@@ -0,0 +1,34 @@
+/**
+ * Copyright 2020, Yahoo Holdings Inc.
```
Comment (jkusa) [inline packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/ReportDeletionHook.kt:2]:
```suggestion
 * Copyright 2021, Yahoo Holdings Inc.
```

**Review by jkusa — APPROVED** [review]

File: packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/DashboardDeletionHook.kt [hunk 2]
```diff
@@ -0,0 +1,34 @@
+/**
+ * Copyright 2020, Yahoo Holdings Inc.
```
Comment (jkusa) [inline packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/DashboardDeletionHook.kt:2]:
```suggestion
 * Copyright 2021, Yahoo Holdings Inc.
```

**Review by kevinhinterlong — APPROVED** [review]

**Review by cythrawll — APPROVED** [review]
