### PR TITLE
Datasource bug

### LINKED ISSUE #1413: Missing datasource breaks entire dashboard (maybe reports too)

### PR DESCRIPTION
**Pull request by holderb5**
Resolves #1413 

## Screenshots
Screen Shot 2021-07-01 at 11 01 49 AM

##License 
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

File: packages/core/addon/mirage/fixtures/dashboard-widget.ts [hunk 1]
```diff
@@ -398,4 +398,84 @@ export default [
...
+                metrics: ['adClicks', 'navClicks'],
+              },
+            },
+          },
+        },
+      },
+    },
+    requests: [
+      {
+        logicalTable: {
```
Comment (kevinhinterlong) [inline packages/core/addon/mirage/fixtures/dashboard-widget.ts:424]: requestv2?

**Review by kevinhinterlong — APPROVED** [review]
🎉

**Review by jkusa — APPROVED** [review]
